#**Prueba de las funciones que hemos implementado**

## Instalación e importación de las librerías y bibliotecas necesarias para las funciones

In [1]:
# Primero instalamos las bibliotecas y/o librerías necesarias para llevar a cabo dicho preprocesamiento

!pip install wfdb

Requirement already satisfied: wfdb in /usr/local/lib/python3.11/dist-packages (4.3.0)
Requirement already satisfied: aiohttp>=3.10.11 in /usr/local/lib/python3.11/dist-packages (from wfdb) (3.11.15)
Requirement already satisfied: fsspec>=2023.10.0 in /usr/local/lib/python3.11/dist-packages (from wfdb) (2025.3.2)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.11/dist-packages (from wfdb) (3.10.0)
Requirement already satisfied: numpy>=1.26.4 in /usr/local/lib/python3.11/dist-packages (from wfdb) (2.0.2)
Requirement already satisfied: pandas>=2.2.3 in /usr/local/lib/python3.11/dist-packages (from wfdb) (2.3.0)
Requirement already satisfied: requests>=2.8.1 in /usr/local/lib/python3.11/dist-packages (from wfdb) (2.32.3)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from wfdb) (1.15.3)
Requirement already satisfied: soundfile>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from wfdb) (0.13.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.10.11->wfdb) (1.20.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.2.2->wfdb) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.2.3->wfdb) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.2.3->wfdb) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.8.1->wfdb) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.8.1->wfdb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.8.1->wfdb) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.8.1->wfdb) (2025.6.15)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile>=0.10.0->wfdb) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile>=0.10.0->wfdb) (2.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->wfdb) (1.17.0)

In [2]:
# Importamos las bibliotecas necesarias para poder trabajar con los distintos conjuntos de datos procedentes de PhysioNet

# Aunque ya se hayan cargado en el archivo de Python con las funciones lo volvemos a hacer por si la importación no ha sido correcta


import pandas as pd
import os
import pickle
import sys

# Carga del archivo .py con las funciones

In [3]:
# Nos montamos a Google Drive para poder cargar los archivos con las funciones necesarias

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
# Añadimos la ruta en la que se enceuntran estos archivos para poder acceder a ellos

sys.path.append('/content/drive/MyDrive/programacion_ECG')

In [5]:
# Importamos las funciones del archivo, para comprobar que funcionan correctamente

from funcionesclasificacionsenales import *
from funcionescargadatos import *

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Función que descarga los archivos de clasificación desde PhysioNet

En primer lugar vamos a crear una función que descargue desde PhysioNet los archivos con extensión '.csv' que recogen la clasificación de los ECG con los que vamos a trabajar. Esto lo necesitamos para posteriormente poder entrenar a nuestra red GAN.

In [6]:
# Comprobamos que la función que hemos creado funciona correctamente

# Tenemos varios archivos .csv en PhysioNet, hay que decidir cual vamos a usar, aunque normalmente se usa el más reciente que es en el que se han corregido los posibles fallos


ruta_physionet = "https://physionet.org/files/challenge-2017/1.0.0/REFERENCE-v3.csv"

ruta_guardado = "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion"



df_reference_v3 = descargar_archivo_clasificacion (ruta_physionet, ruta_guardado, "REFERENCE-v3.csv")

print (df_reference_v3.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
El archivo .csv se ha guardado correctamente en la ruta pasada como argumento: /content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/REFERENCE-v3.csv
        0  1
0  A00001  N
1  A00002  N
2  A00003  N
3  A00004  A
4  A00005  A

# Función que carga el archivo de clasificación en el entorno de ejecución

Esta función nos sirve tanto para cargar un archivo con los valores de clasificación (N, O, A, ~) como para cargar el archivo específico que contiene únicamente las señales de 1 tipo

In [7]:
# Prueba de que la función es correcta

carga_archivo_clasificacion ("/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion", nombre_generico = "REFERENCE-v3", verbose = True)

Archivo cargado: REFERENCE-v3.csv
Ruta en Drive del archivo: /content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/REFERENCE-v3.csv
Dimensiones del DataFrame: (8528, 2)
        0  1
0  A00001  N
1  A00002  N
2  A00003  N
3  A00004  A
4  A00005  A

           0  1
0     A00001  N
1     A00002  N
2     A00003  N
3     A00004  A
4     A00005  A
...      ... ..
8523  A08524  N
8524  A08525  O
8525  A08526  N
8526  A08527  N
8527  A08528  N

[8528 rows x 2 columns]

# Función que modifica el DataFrame para la clasificación

In [8]:
#Hacemos una prueba de que la función es correcta y funciona:

cols = ["ID", "Valor_señal"]

obtener_parametros_df (df_reference_v3, cols, True)

Valor_señal
N    5076
O    2415
A     758
~     279
Name: count, dtype: int64
8528

          ID Valor_señal
0     A00001           N
1     A00002           N
2     A00003           N
3     A00004           A
4     A00005           A
...      ...         ...
8523  A08524           N
8524  A08525           O
8525  A08526           N
8526  A08527           N
8527  A08528           N

[8528 rows x 2 columns]

# Función que obtiene un archivo con los datos de una determinada clase

In [9]:
# Instauramos la variable que contiene los nombres de las columnas del DataFrame

columnas = ["id", "clasificacion"]

In [10]:
# Modificamos el DataFrame con los nombres de las columnas

obtener_parametros_df (df_reference_v3, columnas, True)

clasificacion
N    5076
O    2415
A     758
~     279
Name: count, dtype: int64
8528

          id clasificacion
0     A00001             N
1     A00002             N
2     A00003             N
3     A00004             A
4     A00005             A
...      ...           ...
8523  A08524             N
8524  A08525             O
8525  A08526             N
8526  A08527             N
8527  A08528             N

[8528 rows x 2 columns]

In [11]:
# Obtenemos un archivo con las señales clasificadas como "N" (normales)

obtener_archivo_valor (df_reference_v3, columnas, "N", ruta_guardado)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
# Obtenemos un archivo con las señales clasificadas como "O" (others)

obtener_archivo_valor (df_reference_v3, columnas, "O", ruta_guardado)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
# Obtenemos un archivo con las señales clasificadas como "A" (fibrilación auricular)

obtener_archivo_valor (df_reference_v3, columnas, "A", ruta_guardado)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
# Obtenemos un archivo con las señales clasificadas como "~" (noise)

obtener_archivo_valor (df_reference_v3, columnas, "~", ruta_guardado)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Función que descarga las señales de una determinada clase

In [15]:
dic = guardar_señales_valor ("/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento", "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/df_clasificacion_O.csv", "/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_O")

Se han truncado las últimas 5000 líneas del flujo de salida.
Se ha cargado el archivo A03233 correctamente.
Se ha cargado el archivo A03234 correctamente.
Se ha cargado el archivo A03235 correctamente.
Se ha cargado el archivo A03236 correctamente.
Se ha cargado el archivo A03237 correctamente.
Se ha cargado el archivo A03238 correctamente.
Se ha cargado el archivo A03239 correctamente.
Se ha cargado el archivo A03240 correctamente.
Se ha cargado el archivo A03241 correctamente.
Se ha cargado el archivo A03242 correctamente.
Se ha cargado el archivo A03243 correctamente.
Se ha cargado el archivo A03244 correctamente.
Se ha cargado el archivo A03245 correctamente.
Se ha cargado el archivo A03246 correctamente.
Se ha cargado el archivo A03247 correctamente.
Se ha cargado el archivo A03248 correctamente.
Se ha cargado el archivo A03249 correctamente.
Se ha cargado el archivo A03250 correctamente.
Se ha cargado el archivo A03251 correctamente.
Se ha cargado el archivo A03252 correctamente.
Se ha cargado el archivo A03253 correctamente.
Se ha cargado el archivo A03254 correctamente.
Se ha cargado el archivo A03255 correctamente.
Se ha cargado el archivo A03256 correctamente.
Se ha cargado el archivo A03257 correctamente.
Se ha cargado el archivo A03258 correctamente.
Se ha cargado el archivo A03259 correctamente.
Se ha cargado el archivo A03260 correctamente.
Se ha cargado el archivo A03261 correctamente.
Se ha cargado el archivo A03262 correctamente.
Se ha cargado el archivo A03263 correctamente.
Se ha cargado el archivo A03264 correctamente.
Se ha cargado el archivo A03265 correctamente.
Se ha cargado el archivo A03266 correctamente.
Se ha cargado el archivo A03267 correctamente.
Se ha cargado el archivo A03268 correctamente.
Se ha cargado el archivo A03269 correctamente.
Se ha cargado el archivo A03270 correctamente.
Se ha cargado el archivo A03271 correctamente.
Se ha cargado el archivo A03272 correctamente.
Se ha cargado el archivo A03273 correctamente.
Se ha cargado el archivo A03274 correctamente.
Se ha cargado el archivo A03275 correctamente.
Se ha cargado el archivo A03276 correctamente.
Se ha cargado el archivo A03277 correctamente.
Se ha cargado el archivo A03278 correctamente.
Se ha cargado el archivo A03279 correctamente.
Se ha cargado el archivo A03280 correctamente.
Se ha cargado el archivo A03281 correctamente.
Se ha cargado el archivo A03282 correctamente.
Se ha cargado el archivo A03283 correctamente.
Se ha cargado el archivo A03284 correctamente.
Se ha cargado el archivo A03285 correctamente.
Se ha cargado el archivo A03286 correctamente.
Se ha cargado el archivo A03287 correctamente.
Se ha cargado el archivo A03288 correctamente.
Se ha cargado el archivo A03289 correctamente.
Se ha cargado el archivo A03290 correctamente.
Se ha cargado el archivo A03291 correctamente.
Se ha cargado el archivo A03292 correctamente.
Se ha cargado el archivo A03293 correctamente.
Se ha cargado el archivo A03294 correctamente.
Se ha cargado el archivo A03295 correctamente.
Se ha cargado el archivo A03296 correctamente.
Se ha cargado el archivo A03297 correctamente.
Se ha cargado el archivo A03298 correctamente.
Se ha cargado el archivo A03299 correctamente.
Se ha cargado el archivo A03300 correctamente.
Se ha cargado el archivo A03301 correctamente.
Se ha cargado el archivo A03302 correctamente.
Se ha cargado el archivo A03303 correctamente.
Se ha cargado el archivo A03304 correctamente.
Se ha cargado el archivo A03305 correctamente.
Se ha cargado el archivo A03306 correctamente.
Se ha cargado el archivo A03307 correctamente.
Se ha cargado el archivo A03308 correctamente.
Se ha cargado el archivo A03309 correctamente.
Se ha cargado el archivo A03310 correctamente.
Se ha cargado el archivo A03311 correctamente.
Se ha cargado el archivo A03312 correctamente.
Se ha cargado el archivo A03313 correctamente.
Se ha cargado el archivo A03314 correctamente.
Se ha cargado el archivo A03315 correctamente.
Se ha cargado el archivo A03316 correctamente.
Se ha cargado el archivo A03317 correctamente.
Se ha cargado el archivo A03318 correctamente.
Se ha cargado el archivo A03319 correctamente.
Se ha cargado el archivo A03320 correctamente.
Se ha cargado el archivo A03321 correctamente.
Se ha cargado el archivo A03322 correctamente.
Se ha cargado el archivo A03323 correctamente.
Se ha cargado el archivo A03324 correctamente.
Se ha cargado el archivo A03325 correctamente.
Se ha cargado el archivo A03326 correctamente.
Se ha cargado el archivo A03327 correctamente.
Se ha cargado el archivo A03328 correctamente.
Se ha cargado el archivo A03329 correctamente.
Se ha cargado el archivo A03330 correctamente.
Se ha cargado el archivo A03331 correctamente.
Se ha cargado el archivo A03332 correctamente.
Se ha cargado el archivo A03333 correctamente.
Se ha cargado el archivo A03334 correctamente.
Se ha cargado el archivo A03335 correctamente.
Se ha cargado el archivo A03336 correctamente.
Se ha cargado el archivo A03337 correctamente.
Se ha cargado el archivo A03338 correctamente.
Se ha cargado el archivo A03339 correctamente.
Se ha cargado el archivo A03340 correctamente.
Se ha cargado el archivo A03341 correctamente.
Se ha cargado el archivo A03342 correctamente.
Se ha cargado el archivo A03343 correctamente.
Se ha cargado el archivo A03344 correctamente.
Se ha cargado el archivo A03345 correctamente.
Se ha cargado el archivo A03346 correctamente.
Se ha cargado el archivo A03347 correctamente.
Se ha cargado el archivo A03348 correctamente.
Se ha cargado el archivo A03349 correctamente.
Se ha cargado el archivo A03350 correctamente.
Se ha cargado el archivo A03351 correctamente.
Se ha cargado el archivo A03352 correctamente.
Se ha cargado el archivo A03353 correctamente.
Se ha cargado el archivo A03354 correctamente.
Se ha cargado el archivo A03355 correctamente.
Se ha cargado el archivo A03356 correctamente.
Se ha cargado el archivo A03357 correctamente.
Se ha cargado el archivo A03358 correctamente.
Se ha cargado el archivo A03359 correctamente.
Se ha cargado el archivo A03360 correctamente.
Se ha cargado el archivo A03361 correctamente.
Se ha cargado el archivo A03362 correctamente.
Se ha cargado el archivo A03363 correctamente.
Se ha cargado el archivo A03364 correctamente.
Se ha cargado el archivo A03365 correctamente.
Se ha cargado el archivo A03366 correctamente.
Se ha cargado el archivo A03367 correctamente.
Se ha cargado el archivo A03368 correctamente.
Se ha cargado el archivo A03369 correctamente.
Se ha cargado el archivo A03370 correctamente.
Se ha cargado el archivo A03371 correctamente.
Se ha cargado el archivo A03372 correctamente.
Se ha cargado el archivo A03373 correctamente.
Se ha cargado el archivo A03374 correctamente.
Se ha cargado el archivo A03375 correctamente.
Se ha cargado el archivo A03376 correctamente.
Se ha cargado el archivo A03377 correctamente.
Se ha cargado el archivo A03378 correctamente.
Se ha cargado el archivo A03379 correctamente.
Se ha cargado el archivo A03380 correctamente.
Se ha cargado el archivo A03381 correctamente.
Se ha cargado el archivo A03382 correctamente.
Se ha cargado el archivo A03383 correctamente.
Se ha cargado el archivo A03384 correctamente.
Se ha cargado el archivo A03385 correctamente.
Se ha cargado el archivo A03386 correctamente.
Se ha cargado el archivo A03387 correctamente.
Se ha cargado el archivo A03388 correctamente.
Se ha cargado el archivo A03389 correctamente.
Se ha cargado el archivo A03390 correctamente.
Se ha cargado el archivo A03391 correctamente.
Se ha cargado el archivo A03392 correctamente.
Se ha cargado el archivo A03393 correctamente.
Se ha cargado el archivo A03394 correctamente.
Se ha cargado el archivo A03395 correctamente.
Se ha cargado el archivo A03396 correctamente.
Se ha cargado el archivo A03397 correctamente.
Se ha cargado el archivo A03398 correctamente.
Se ha cargado el archivo A03399 correctamente.
Se ha cargado el archivo A03400 correctamente.
Se ha cargado el archivo A03401 correctamente.
Se ha cargado el archivo A03402 correctamente.
Se ha cargado el archivo A03403 correctamente.
Se ha cargado el archivo A03404 correctamente.
Se ha cargado el archivo A03405 correctamente.
Se ha cargado el archivo A03406 correctamente.
Se ha cargado el archivo A03407 correctamente.
Se ha cargado el archivo A03408 correctamente.
Se ha cargado el archivo A03409 correctamente.
Se ha cargado el archivo A03410 correctamente.
Se ha cargado el archivo A03411 correctamente.
Se ha cargado el archivo A03412 correctamente.
Se ha cargado el archivo A03413 correctamente.
Se ha cargado el archivo A03414 correctamente.
Se ha cargado el archivo A03415 correctamente.
Se ha cargado el archivo A03416 correctamente.
Se ha cargado el archivo A03417 correctamente.
Se ha cargado el archivo A03418 correctamente.
Se ha cargado el archivo A03419 correctamente.
Se ha cargado el archivo A03420 correctamente.
Se ha cargado el archivo A03421 correctamente.
Se ha cargado el archivo A03422 correctamente.
Se ha cargado el archivo A03423 correctamente.
Se ha cargado el archivo A03424 correctamente.
Se ha cargado el archivo A03425 correctamente.
Se ha cargado el archivo A03426 correctamente.
Se ha cargado el archivo A03427 correctamente.
Se ha cargado el archivo A03428 correctamente.
Se ha cargado el archivo A03429 correctamente.
Se ha cargado el archivo A03430 correctamente.
Se ha cargado el archivo A03431 correctamente.
Se ha cargado el archivo A03432 correctamente.
Se ha cargado el archivo A03433 correctamente.
Se ha cargado el archivo A03434 correctamente.
Se ha cargado el archivo A03435 correctamente.
Se ha cargado el archivo A03436 correctamente.
Se ha cargado el archivo A03437 correctamente.
Se ha cargado el archivo A03438 correctamente.
Se ha cargado el archivo A03439 correctamente.
Se ha cargado el archivo A03440 correctamente.
Se ha cargado el archivo A03441 correctamente.
Se ha cargado el archivo A03442 correctamente.
Se ha cargado el archivo A03443 correctamente.
Se ha cargado el archivo A03444 correctamente.
Se ha cargado el archivo A03445 correctamente.
Se ha cargado el archivo A03446 correctamente.
Se ha cargado el archivo A03447 correctamente.
Se ha cargado el archivo A03448 correctamente.
Se ha cargado el archivo A03449 correctamente.
Se ha cargado el archivo A03450 correctamente.
Se ha cargado el archivo A03451 correctamente.
Se ha cargado el archivo A03452 correctamente.
Se ha cargado el archivo A03453 correctamente.
Se ha cargado el archivo A03454 correctamente.
Se ha cargado el archivo A03455 correctamente.
Se ha cargado el archivo A03456 correctamente.
Se ha cargado el archivo A03457 correctamente.
Se ha cargado el archivo A03458 correctamente.
Se ha cargado el archivo A03459 correctamente.
Se ha cargado el archivo A03460 correctamente.
Se ha cargado el archivo A03461 correctamente.
Se ha cargado el archivo A03462 correctamente.
Se ha cargado el archivo A03463 correctamente.
Se ha cargado el archivo A03464 correctamente.
Se ha cargado el archivo A03465 correctamente.
Se ha cargado el archivo A03466 correctamente.
Se ha cargado el archivo A03467 correctamente.
Se ha cargado el archivo A03468 correctamente.
Se ha cargado el archivo A03469 correctamente.
Se ha cargado el archivo A03470 correctamente.
Se ha cargado el archivo A03471 correctamente.
Se ha cargado el archivo A03472 correctamente.
Se ha cargado el archivo A03473 correctamente.
Se ha cargado el archivo A03474 correctamente.
Se ha cargado el archivo A03475 correctamente.
Se ha cargado el archivo A03476 correctamente.
Se ha cargado el archivo A03477 correctamente.
Se ha cargado el archivo A03478 correctamente.
Se ha cargado el archivo A03479 correctamente.
Se ha cargado el archivo A03480 correctamente.
Se ha cargado el archivo A03481 correctamente.
Se ha cargado el archivo A03482 correctamente.
Se ha cargado el archivo A03483 correctamente.
Se ha cargado el archivo A03484 correctamente.
Se ha cargado el archivo A03485 correctamente.
Se ha cargado el archivo A03486 correctamente.
Se ha cargado el archivo A03487 correctamente.
Se ha cargado el archivo A03488 correctamente.
Se ha cargado el archivo A03489 correctamente.
Se ha cargado el archivo A03490 correctamente.
Se ha cargado el archivo A03491 correctamente.
Se ha cargado el archivo A03492 correctamente.
Se ha cargado el archivo A03493 correctamente.
Se ha cargado el archivo A03494 correctamente.
Se ha cargado el archivo A03495 correctamente.
Se ha cargado el archivo A03496 correctamente.
Se ha cargado el archivo A03497 correctamente.
Se ha cargado el archivo A03498 correctamente.
Se ha cargado el archivo A03499 correctamente.
Se ha cargado el archivo A03500 correctamente.
Se ha cargado el archivo A03501 correctamente.
Se ha cargado el archivo A03502 correctamente.
Se ha cargado el archivo A03503 correctamente.
Se ha cargado el archivo A03504 correctamente.
Se ha cargado el archivo A03505 correctamente.
Se ha cargado el archivo A03506 correctamente.
Se ha cargado el archivo A03507 correctamente.
Se ha cargado el archivo A03508 correctamente.
Se ha cargado el archivo A03509 correctamente.
Se ha cargado el archivo A03510 correctamente.
Se ha cargado el archivo A03511 correctamente.
Se ha cargado el archivo A03512 correctamente.
Se ha cargado el archivo A03513 correctamente.
Se ha cargado el archivo A03514 correctamente.
Se ha cargado el archivo A03515 correctamente.
Se ha cargado el archivo A03516 correctamente.
Se ha cargado el archivo A03517 correctamente.
Se ha cargado el archivo A03518 correctamente.
Se ha cargado el archivo A03519 correctamente.
Se ha cargado el archivo A03520 correctamente.
Se ha cargado el archivo A03521 correctamente.
Se ha cargado el archivo A03522 correctamente.
Se ha cargado el archivo A03523 correctamente.
Se ha cargado el archivo A03524 correctamente.
Se ha cargado el archivo A03525 correctamente.
Se ha cargado el archivo A03526 correctamente.
Se ha cargado el archivo A03527 correctamente.
Se ha cargado el archivo A03528 correctamente.
Se ha cargado el archivo A03529 correctamente.
Se ha cargado el archivo A03530 correctamente.
Se ha cargado el archivo A03531 correctamente.
Se ha cargado el archivo A03532 correctamente.
Se ha cargado el archivo A03533 correctamente.
Se ha cargado el archivo A03534 correctamente.
Se ha cargado el archivo A03535 correctamente.
Se ha cargado el archivo A03536 correctamente.
Se ha cargado el archivo A03537 correctamente.
Se ha cargado el archivo A03538 correctamente.
Se ha cargado el archivo A03539 correctamente.
Se ha cargado el archivo A03540 correctamente.
Se ha cargado el archivo A03541 correctamente.
Se ha cargado el archivo A03542 correctamente.
Se ha cargado el archivo A03543 correctamente.
Se ha cargado el archivo A03544 correctamente.
Se ha cargado el archivo A03545 correctamente.
Se ha cargado el archivo A03546 correctamente.
Se ha cargado el archivo A03547 correctamente.
Se ha cargado el archivo A03548 correctamente.
Se ha cargado el archivo A03549 correctamente.
Se ha cargado el archivo A03550 correctamente.
Se ha cargado el archivo A03551 correctamente.
Se ha cargado el archivo A03552 correctamente.
Se ha cargado el archivo A03553 correctamente.
Se ha cargado el archivo A03554 correctamente.
Se ha cargado el archivo A03555 correctamente.
Se ha cargado el archivo A03556 correctamente.
Se ha cargado el archivo A03557 correctamente.
Se ha cargado el archivo A03558 correctamente.
Se ha cargado el archivo A03559 correctamente.
Se ha cargado el archivo A03560 correctamente.
Se ha cargado el archivo A03561 correctamente.
Se ha cargado el archivo A03562 correctamente.
Se ha cargado el archivo A03563 correctamente.
Se ha cargado el archivo A03564 correctamente.
Se ha cargado el archivo A03565 correctamente.
Se ha cargado el archivo A03566 correctamente.
Se ha cargado el archivo A03567 correctamente.
Se ha cargado el archivo A03568 correctamente.
Se ha cargado el archivo A03569 correctamente.
Se ha cargado el archivo A03570 correctamente.
Se ha cargado el archivo A03571 correctamente.
Se ha cargado el archivo A03572 correctamente.
Se ha cargado el archivo A03573 correctamente.
Se ha cargado el archivo A03574 correctamente.
Se ha cargado el archivo A03575 correctamente.
Se ha cargado el archivo A03576 correctamente.
Se ha cargado el archivo A03577 correctamente.
Se ha cargado el archivo A03578 correctamente.
Se ha cargado el archivo A03579 correctamente.
Se ha cargado el archivo A03580 correctamente.
Se ha cargado el archivo A03581 correctamente.
Se ha cargado el archivo A03582 correctamente.
Se ha cargado el archivo A03583 correctamente.
Se ha cargado el archivo A03584 correctamente.
Se ha cargado el archivo A03585 correctamente.
Se ha cargado el archivo A03586 correctamente.
Se ha cargado el archivo A03587 correctamente.
Se ha cargado el archivo A03588 correctamente.
Se ha cargado el archivo A03589 correctamente.
Se ha cargado el archivo A03590 correctamente.
Se ha cargado el archivo A03591 correctamente.
Se ha cargado el archivo A03592 correctamente.
Se ha cargado el archivo A03593 correctamente.
Se ha cargado el archivo A03594 correctamente.
Se ha cargado el archivo A03595 correctamente.
Se ha cargado el archivo A03596 correctamente.
Se ha cargado el archivo A03597 correctamente.
Se ha cargado el archivo A03598 correctamente.
Se ha cargado el archivo A03599 correctamente.
Se ha cargado el archivo A03600 correctamente.
Se ha cargado el archivo A03601 correctamente.
Se ha cargado el archivo A03602 correctamente.
Se ha cargado el archivo A03603 correctamente.
Se ha cargado el archivo A03604 correctamente.
Se ha cargado el archivo A03605 correctamente.
Se ha cargado el archivo A03606 correctamente.
Se ha cargado el archivo A03607 correctamente.
Se ha cargado el archivo A03608 correctamente.
Se ha cargado el archivo A03609 correctamente.
Se ha cargado el archivo A03610 correctamente.
Se ha cargado el archivo A03611 correctamente.
Se ha cargado el archivo A03612 correctamente.
Se ha cargado el archivo A03613 correctamente.
Se ha cargado el archivo A03614 correctamente.
Se ha cargado el archivo A03615 correctamente.
Se ha cargado el archivo A03616 correctamente.
Se ha cargado el archivo A03617 correctamente.
Se ha cargado el archivo A03618 correctamente.
Se ha cargado el archivo A03619 correctamente.
Se ha cargado el archivo A03620 correctamente.
Se ha cargado el archivo A03621 correctamente.
Se ha cargado el archivo A03622 correctamente.
Se ha cargado el archivo A03623 correctamente.
Se ha cargado el archivo A03624 correctamente.
Se ha cargado el archivo A03625 correctamente.
Se ha cargado el archivo A03626 correctamente.
Se ha cargado el archivo A03627 correctamente.
Se ha cargado el archivo A03628 correctamente.
Se ha cargado el archivo A03629 correctamente.
Se ha cargado el archivo A03630 correctamente.
Se ha cargado el archivo A03631 correctamente.
Se ha cargado el archivo A03632 correctamente.
Se ha cargado el archivo A03633 correctamente.
Se ha cargado el archivo A03634 correctamente.
Se ha cargado el archivo A03635 correctamente.
Se ha cargado el archivo A03636 correctamente.
Se ha cargado el archivo A03637 correctamente.
Se ha cargado el archivo A03638 correctamente.
Se ha cargado el archivo A03639 correctamente.
Se ha cargado el archivo A03640 correctamente.
Se ha cargado el archivo A03641 correctamente.
Se ha cargado el archivo A03642 correctamente.
Se ha cargado el archivo A03643 correctamente.
Se ha cargado el archivo A03644 correctamente.
Se ha cargado el archivo A03645 correctamente.
Se ha cargado el archivo A03646 correctamente.
Se ha cargado el archivo A03647 correctamente.
Se ha cargado el archivo A03648 correctamente.
Se ha cargado el archivo A03649 correctamente.
Se ha cargado el archivo A03650 correctamente.
Se ha cargado el archivo A03651 correctamente.
Se ha cargado el archivo A03652 correctamente.
Se ha cargado el archivo A03653 correctamente.
Se ha cargado el archivo A03654 correctamente.
Se ha cargado el archivo A03655 correctamente.
Se ha cargado el archivo A03656 correctamente.

In [ ]:
dic1 = guardar_señales_valor ("/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento", "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/df_clasificacion_A.csv", "/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_A")

Se han truncado las últimas 5000 líneas del flujo de salida.
Se ha cargado el archivo A03233 correctamente.
Se ha cargado el archivo A03234 correctamente.
Se ha cargado el archivo A03235 correctamente.
Se ha cargado el archivo A03236 correctamente.
Se ha cargado el archivo A03237 correctamente.
Se ha cargado el archivo A03238 correctamente.
Se ha cargado el archivo A03239 correctamente.
Se ha cargado el archivo A03240 correctamente.
Se ha cargado el archivo A03241 correctamente.
Se ha cargado el archivo A03242 correctamente.
Se ha cargado el archivo A03243 correctamente.
Se ha cargado el archivo A03244 correctamente.
Se ha cargado el archivo A03245 correctamente.
Se ha cargado el archivo A03246 correctamente.
Se ha cargado el archivo A03247 correctamente.
Se ha cargado el archivo A03248 correctamente.
Se ha cargado el archivo A03249 correctamente.
Se ha cargado el archivo A03250 correctamente.
Se ha cargado el archivo A03251 correctamente.
Se ha cargado el archivo A03252 correctamente.
Se ha cargado el archivo A03253 correctamente.
Se ha cargado el archivo A03254 correctamente.
Se ha cargado el archivo A03255 correctamente.
Se ha cargado el archivo A03256 correctamente.
Se ha cargado el archivo A03257 correctamente.
Se ha cargado el archivo A03258 correctamente.
Se ha cargado el archivo A03259 correctamente.
Se ha cargado el archivo A03260 correctamente.
Se ha cargado el archivo A03261 correctamente.
Se ha cargado el archivo A03262 correctamente.
Se ha cargado el archivo A03263 correctamente.
Se ha cargado el archivo A03264 correctamente.
Se ha cargado el archivo A03265 correctamente.
Se ha cargado el archivo A03266 correctamente.
Se ha cargado el archivo A03267 correctamente.
Se ha cargado el archivo A03268 correctamente.
Se ha cargado el archivo A03269 correctamente.
Se ha cargado el archivo A03270 correctamente.
Se ha cargado el archivo A03271 correctamente.
Se ha cargado el archivo A03272 correctamente.
Se ha cargado el archivo A03273 correctamente.
Se ha cargado el archivo A03274 correctamente.
Se ha cargado el archivo A03275 correctamente.
Se ha cargado el archivo A03276 correctamente.
Se ha cargado el archivo A03277 correctamente.
Se ha cargado el archivo A03278 correctamente.
Se ha cargado el archivo A03279 correctamente.
Se ha cargado el archivo A03280 correctamente.
Se ha cargado el archivo A03281 correctamente.
Se ha cargado el archivo A03282 correctamente.
Se ha cargado el archivo A03283 correctamente.
Se ha cargado el archivo A03284 correctamente.
Se ha cargado el archivo A03285 correctamente.
Se ha cargado el archivo A03286 correctamente.
Se ha cargado el archivo A03287 correctamente.
Se ha cargado el archivo A03288 correctamente.
Se ha cargado el archivo A03289 correctamente.
Se ha cargado el archivo A03290 correctamente.
Se ha cargado el archivo A03291 correctamente.
Se ha cargado el archivo A03292 correctamente.
Se ha cargado el archivo A03293 correctamente.
Se ha cargado el archivo A03294 correctamente.
Se ha cargado el archivo A03295 correctamente.
Se ha cargado el archivo A03296 correctamente.
Se ha cargado el archivo A03297 correctamente.
Se ha cargado el archivo A03298 correctamente.
Se ha cargado el archivo A03299 correctamente.
Se ha cargado el archivo A03300 correctamente.
Se ha cargado el archivo A03301 correctamente.
Se ha cargado el archivo A03302 correctamente.
Se ha cargado el archivo A03303 correctamente.
Se ha cargado el archivo A03304 correctamente.
Se ha cargado el archivo A03305 correctamente.
Se ha cargado el archivo A03306 correctamente.
Se ha cargado el archivo A03307 correctamente.
Se ha cargado el archivo A03308 correctamente.
Se ha cargado el archivo A03309 correctamente.
Se ha cargado el archivo A03310 correctamente.
Se ha cargado el archivo A03311 correctamente.
Se ha cargado el archivo A03312 correctamente.
Se ha cargado el archivo A03313 correctamente.
Se ha cargado el archivo A03314 correctamente.
Se ha cargado el archivo A03315 correctamente.
Se ha cargado el archivo A03316 correctamente.
Se ha cargado el archivo A03317 correctamente.
Se ha cargado el archivo A03318 correctamente.
Se ha cargado el archivo A03319 correctamente.
Se ha cargado el archivo A03320 correctamente.
Se ha cargado el archivo A03321 correctamente.
Se ha cargado el archivo A03322 correctamente.
Se ha cargado el archivo A03323 correctamente.
Se ha cargado el archivo A03324 correctamente.
Se ha cargado el archivo A03325 correctamente.
Se ha cargado el archivo A03326 correctamente.
Se ha cargado el archivo A03327 correctamente.
Se ha cargado el archivo A03328 correctamente.
Se ha cargado el archivo A03329 correctamente.
Se ha cargado el archivo A03330 correctamente.
Se ha cargado el archivo A03331 correctamente.
Se ha cargado el archivo A03332 correctamente.
Se ha cargado el archivo A03333 correctamente.
Se ha cargado el archivo A03334 correctamente.
Se ha cargado el archivo A03335 correctamente.
Se ha cargado el archivo A03336 correctamente.
Se ha cargado el archivo A03337 correctamente.
Se ha cargado el archivo A03338 correctamente.
Se ha cargado el archivo A03339 correctamente.
Se ha cargado el archivo A03340 correctamente.
Se ha cargado el archivo A03341 correctamente.
Se ha cargado el archivo A03342 correctamente.
Se ha cargado el archivo A03343 correctamente.
Se ha cargado el archivo A03344 correctamente.
Se ha cargado el archivo A03345 correctamente.
Se ha cargado el archivo A03346 correctamente.
Se ha cargado el archivo A03347 correctamente.
Se ha cargado el archivo A03348 correctamente.
Se ha cargado el archivo A03349 correctamente.
Se ha cargado el archivo A03350 correctamente.
Se ha cargado el archivo A03351 correctamente.
Se ha cargado el archivo A03352 correctamente.
Se ha cargado el archivo A03353 correctamente.
Se ha cargado el archivo A03354 correctamente.
Se ha cargado el archivo A03355 correctamente.
Se ha cargado el archivo A03356 correctamente.
Se ha cargado el archivo A03357 correctamente.
Se ha cargado el archivo A03358 correctamente.
Se ha cargado el archivo A03359 correctamente.
Se ha cargado el archivo A03360 correctamente.
Se ha cargado el archivo A03361 correctamente.
Se ha cargado el archivo A03362 correctamente.
Se ha cargado el archivo A03363 correctamente.
Se ha cargado el archivo A03364 correctamente.
Se ha cargado el archivo A03365 correctamente.
Se ha cargado el archivo A03366 correctamente.
Se ha cargado el archivo A03367 correctamente.
Se ha cargado el archivo A03368 correctamente.
Se ha cargado el archivo A03369 correctamente.
Se ha cargado el archivo A03370 correctamente.
Se ha cargado el archivo A03371 correctamente.
Se ha cargado el archivo A03372 correctamente.
Se ha cargado el archivo A03373 correctamente.
Se ha cargado el archivo A03374 correctamente.
Se ha cargado el archivo A03375 correctamente.
Se ha cargado el archivo A03376 correctamente.
Se ha cargado el archivo A03377 correctamente.
Se ha cargado el archivo A03378 correctamente.
Se ha cargado el archivo A03379 correctamente.
Se ha cargado el archivo A03380 correctamente.
Se ha cargado el archivo A03381 correctamente.
Se ha cargado el archivo A03382 correctamente.
Se ha cargado el archivo A03383 correctamente.
Se ha cargado el archivo A03384 correctamente.
Se ha cargado el archivo A03385 correctamente.
Se ha cargado el archivo A03386 correctamente.
Se ha cargado el archivo A03387 correctamente.
Se ha cargado el archivo A03388 correctamente.
Se ha cargado el archivo A03389 correctamente.
Se ha cargado el archivo A03390 correctamente.
Se ha cargado el archivo A03391 correctamente.
Se ha cargado el archivo A03392 correctamente.
Se ha cargado el archivo A03393 correctamente.
Se ha cargado el archivo A03394 correctamente.
Se ha cargado el archivo A03395 correctamente.
Se ha cargado el archivo A03396 correctamente.
Se ha cargado el archivo A03397 correctamente.
Se ha cargado el archivo A03398 correctamente.
Se ha cargado el archivo A03399 correctamente.
Se ha cargado el archivo A03400 correctamente.
Se ha cargado el archivo A03401 correctamente.
Se ha cargado el archivo A03402 correctamente.
Se ha cargado el archivo A03403 correctamente.
Se ha cargado el archivo A03404 correctamente.
Se ha cargado el archivo A03405 correctamente.
Se ha cargado el archivo A03406 correctamente.
Se ha cargado el archivo A03407 correctamente.
Se ha cargado el archivo A03408 correctamente.
Se ha cargado el archivo A03409 correctamente.
Se ha cargado el archivo A03410 correctamente.
Se ha cargado el archivo A03411 correctamente.
Se ha cargado el archivo A03412 correctamente.
Se ha cargado el archivo A03413 correctamente.
Se ha cargado el archivo A03414 correctamente.
Se ha cargado el archivo A03415 correctamente.
Se ha cargado el archivo A03416 correctamente.
Se ha cargado el archivo A03417 correctamente.
Se ha cargado el archivo A03418 correctamente.
Se ha cargado el archivo A03419 correctamente.
Se ha cargado el archivo A03420 correctamente.
Se ha cargado el archivo A03421 correctamente.
Se ha cargado el archivo A03422 correctamente.
Se ha cargado el archivo A03423 correctamente.
Se ha cargado el archivo A03424 correctamente.
Se ha cargado el archivo A03425 correctamente.
Se ha cargado el archivo A03426 correctamente.
Se ha cargado el archivo A03427 correctamente.
Se ha cargado el archivo A03428 correctamente.
Se ha cargado el archivo A03429 correctamente.
Se ha cargado el archivo A03430 correctamente.
Se ha cargado el archivo A03431 correctamente.
Se ha cargado el archivo A03432 correctamente.
Se ha cargado el archivo A03433 correctamente.
Se ha cargado el archivo A03434 correctamente.
Se ha cargado el archivo A03435 correctamente.
Se ha cargado el archivo A03436 correctamente.
Se ha cargado el archivo A03437 correctamente.
Se ha cargado el archivo A03438 correctamente.
Se ha cargado el archivo A03439 correctamente.
Se ha cargado el archivo A03440 correctamente.
Se ha cargado el archivo A03441 correctamente.
Se ha cargado el archivo A03442 correctamente.
Se ha cargado el archivo A03443 correctamente.
Se ha cargado el archivo A03444 correctamente.
Se ha cargado el archivo A03445 correctamente.
Se ha cargado el archivo A03446 correctamente.
Se ha cargado el archivo A03447 correctamente.
Se ha cargado el archivo A03448 correctamente.
Se ha cargado el archivo A03449 correctamente.
Se ha cargado el archivo A03450 correctamente.
Se ha cargado el archivo A03451 correctamente.
Se ha cargado el archivo A03452 correctamente.
Se ha cargado el archivo A03453 correctamente.
Se ha cargado el archivo A03454 correctamente.
Se ha cargado el archivo A03455 correctamente.
Se ha cargado el archivo A03456 correctamente.
Se ha cargado el archivo A03457 correctamente.
Se ha cargado el archivo A03458 correctamente.
Se ha cargado el archivo A03459 correctamente.
Se ha cargado el archivo A03460 correctamente.
Se ha cargado el archivo A03461 correctamente.
Se ha cargado el archivo A03462 correctamente.
Se ha cargado el archivo A03463 correctamente.
Se ha cargado el archivo A03464 correctamente.
Se ha cargado el archivo A03465 correctamente.
Se ha cargado el archivo A03466 correctamente.
Se ha cargado el archivo A03467 correctamente.
Se ha cargado el archivo A03468 correctamente.
Se ha cargado el archivo A03469 correctamente.
Se ha cargado el archivo A03470 correctamente.
Se ha cargado el archivo A03471 correctamente.
Se ha cargado el archivo A03472 correctamente.
Se ha cargado el archivo A03473 correctamente.
Se ha cargado el archivo A03474 correctamente.
Se ha cargado el archivo A03475 correctamente.
Se ha cargado el archivo A03476 correctamente.
Se ha cargado el archivo A03477 correctamente.
Se ha cargado el archivo A03478 correctamente.
Se ha cargado el archivo A03479 correctamente.
Se ha cargado el archivo A03480 correctamente.
Se ha cargado el archivo A03481 correctamente.
Se ha cargado el archivo A03482 correctamente.
Se ha cargado el archivo A03483 correctamente.
Se ha cargado el archivo A03484 correctamente.
Se ha cargado el archivo A03485 correctamente.
Se ha cargado el archivo A03486 correctamente.
Se ha cargado el archivo A03487 correctamente.
Se ha cargado el archivo A03488 correctamente.
Se ha cargado el archivo A03489 correctamente.
Se ha cargado el archivo A03490 correctamente.
Se ha cargado el archivo A03491 correctamente.
Se ha cargado el archivo A03492 correctamente.
Se ha cargado el archivo A03493 correctamente.
Se ha cargado el archivo A03494 correctamente.
Se ha cargado el archivo A03495 correctamente.
Se ha cargado el archivo A03496 correctamente.
Se ha cargado el archivo A03497 correctamente.
Se ha cargado el archivo A03498 correctamente.
Se ha cargado el archivo A03499 correctamente.
Se ha cargado el archivo A03500 correctamente.
Se ha cargado el archivo A03501 correctamente.
Se ha cargado el archivo A03502 correctamente.
Se ha cargado el archivo A03503 correctamente.
Se ha cargado el archivo A03504 correctamente.
Se ha cargado el archivo A03505 correctamente.
Se ha cargado el archivo A03506 correctamente.
Se ha cargado el archivo A03507 correctamente.
Se ha cargado el archivo A03508 correctamente.
Se ha cargado el archivo A03509 correctamente.
Se ha cargado el archivo A03510 correctamente.
Se ha cargado el archivo A03511 correctamente.
Se ha cargado el archivo A03512 correctamente.
Se ha cargado el archivo A03513 correctamente.
Se ha cargado el archivo A03514 correctamente.
Se ha cargado el archivo A03515 correctamente.
Se ha cargado el archivo A03516 correctamente.
Se ha cargado el archivo A03517 correctamente.
Se ha cargado el archivo A03518 correctamente.
Se ha cargado el archivo A03519 correctamente.
Se ha cargado el archivo A03520 correctamente.
Se ha cargado el archivo A03521 correctamente.
Se ha cargado el archivo A03522 correctamente.
Se ha cargado el archivo A03523 correctamente.
Se ha cargado el archivo A03524 correctamente.
Se ha cargado el archivo A03525 correctamente.
Se ha cargado el archivo A03526 correctamente.
Se ha cargado el archivo A03527 correctamente.
Se ha cargado el archivo A03528 correctamente.
Se ha cargado el archivo A03529 correctamente.
Se ha cargado el archivo A03530 correctamente.
Se ha cargado el archivo A03531 correctamente.
Se ha cargado el archivo A03532 correctamente.
Se ha cargado el archivo A03533 correctamente.
Se ha cargado el archivo A03534 correctamente.
Se ha cargado el archivo A03535 correctamente.
Se ha cargado el archivo A03536 correctamente.
Se ha cargado el archivo A03537 correctamente.
Se ha cargado el archivo A03538 correctamente.
Se ha cargado el archivo A03539 correctamente.
Se ha cargado el archivo A03540 correctamente.
Se ha cargado el archivo A03541 correctamente.
Se ha cargado el archivo A03542 correctamente.
Se ha cargado el archivo A03543 correctamente.
Se ha cargado el archivo A03544 correctamente.
Se ha cargado el archivo A03545 correctamente.
Se ha cargado el archivo A03546 correctamente.
Se ha cargado el archivo A03547 correctamente.
Se ha cargado el archivo A03548 correctamente.
Se ha cargado el archivo A03549 correctamente.
Se ha cargado el archivo A03550 correctamente.
Se ha cargado el archivo A03551 correctamente.
Se ha cargado el archivo A03552 correctamente.
Se ha cargado el archivo A03553 correctamente.
Se ha cargado el archivo A03554 correctamente.
Se ha cargado el archivo A03555 correctamente.
Se ha cargado el archivo A03556 correctamente.
Se ha cargado el archivo A03557 correctamente.
Se ha cargado el archivo A03558 correctamente.
Se ha cargado el archivo A03559 correctamente.
Se ha cargado el archivo A03560 correctamente.
Se ha cargado el archivo A03561 correctamente.
Se ha cargado el archivo A03562 correctamente.
Se ha cargado el archivo A03563 correctamente.
Se ha cargado el archivo A03564 correctamente.
Se ha cargado el archivo A03565 correctamente.
Se ha cargado el archivo A03566 correctamente.
Se ha cargado el archivo A03567 correctamente.
Se ha cargado el archivo A03568 correctamente.
Se ha cargado el archivo A03569 correctamente.
Se ha cargado el archivo A03570 correctamente.
Se ha cargado el archivo A03571 correctamente.
Se ha cargado el archivo A03572 correctamente.
Se ha cargado el archivo A03573 correctamente.
Se ha cargado el archivo A03574 correctamente.
Se ha cargado el archivo A03575 correctamente.
Se ha cargado el archivo A03576 correctamente.
Se ha cargado el archivo A03577 correctamente.
Se ha cargado el archivo A03578 correctamente.
Se ha cargado el archivo A03579 correctamente.
Se ha cargado el archivo A03580 correctamente.
Se ha cargado el archivo A03581 correctamente.
Se ha cargado el archivo A03582 correctamente.
Se ha cargado el archivo A03583 correctamente.
Se ha cargado el archivo A03584 correctamente.
Se ha cargado el archivo A03585 correctamente.
Se ha cargado el archivo A03586 correctamente.
Se ha cargado el archivo A03587 correctamente.
Se ha cargado el archivo A03588 correctamente.
Se ha cargado el archivo A03589 correctamente.
Se ha cargado el archivo A03590 correctamente.
Se ha cargado el archivo A03591 correctamente.
Se ha cargado el archivo A03592 correctamente.
Se ha cargado el archivo A03593 correctamente.
Se ha cargado el archivo A03594 correctamente.
Se ha cargado el archivo A03595 correctamente.
Se ha cargado el archivo A03596 correctamente.
Se ha cargado el archivo A03597 correctamente.
Se ha cargado el archivo A03598 correctamente.
Se ha cargado el archivo A03599 correctamente.
Se ha cargado el archivo A03600 correctamente.
Se ha cargado el archivo A03601 correctamente.
Se ha cargado el archivo A03602 correctamente.
Se ha cargado el archivo A03603 correctamente.
Se ha cargado el archivo A03604 correctamente.
Se ha cargado el archivo A03605 correctamente.
Se ha cargado el archivo A03606 correctamente.
Se ha cargado el archivo A03607 correctamente.
Se ha cargado el archivo A03608 correctamente.
Se ha cargado el archivo A03609 correctamente.
Se ha cargado el archivo A03610 correctamente.
Se ha cargado el archivo A03611 correctamente.
Se ha cargado el archivo A03612 correctamente.
Se ha cargado el archivo A03613 correctamente.
Se ha cargado el archivo A03614 correctamente.
Se ha cargado el archivo A03615 correctamente.
Se ha cargado el archivo A03616 correctamente.
Se ha cargado el archivo A03617 correctamente.
Se ha cargado el archivo A03618 correctamente.
Se ha cargado el archivo A03619 correctamente.
Se ha cargado el archivo A03620 correctamente.
Se ha cargado el archivo A03621 correctamente.
Se ha cargado el archivo A03622 correctamente.
Se ha cargado el archivo A03623 correctamente.
Se ha cargado el archivo A03624 correctamente.
Se ha cargado el archivo A03625 correctamente.
Se ha cargado el archivo A03626 correctamente.
Se ha cargado el archivo A03627 correctamente.
Se ha cargado el archivo A03628 correctamente.
Se ha cargado el archivo A03629 correctamente.
Se ha cargado el archivo A03630 correctamente.
Se ha cargado el archivo A03631 correctamente.
Se ha cargado el archivo A03632 correctamente.
Se ha cargado el archivo A03633 correctamente.
Se ha cargado el archivo A03634 correctamente.
Se ha cargado el archivo A03635 correctamente.
Se ha cargado el archivo A03636 correctamente.
Se ha cargado el archivo A03637 correctamente.
Se ha cargado el archivo A03638 correctamente.
Se ha cargado el archivo A03639 correctamente.
Se ha cargado el archivo A03640 correctamente.
Se ha cargado el archivo A03641 correctamente.
Se ha cargado el archivo A03642 correctamente.
Se ha cargado el archivo A03643 correctamente.
Se ha cargado el archivo A03644 correctamente.
Se ha cargado el archivo A03645 correctamente.
Se ha cargado el archivo A03646 correctamente.
Se ha cargado el archivo A03647 correctamente.
Se ha cargado el archivo A03648 correctamente.
Se ha cargado el archivo A03649 correctamente.
Se ha cargado el archivo A03650 correctamente.
Se ha cargado el archivo A03651 correctamente.
Se ha cargado el archivo A03652 correctamente.
Se ha cargado el archivo A03653 correctamente.
Se ha cargado el archivo A03654 correctamente.
Se ha cargado el archivo A03655 correctamente.
Se ha cargado el archivo A03656 correctamente.

In [ ]:
dic2 = guardar_señales_valor ("/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento", "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/df_clasificacion_N.csv", "/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_N")

Se han truncado las últimas 5000 líneas del flujo de salida.
Se ha cargado el archivo A03233 correctamente.
Se ha cargado el archivo A03234 correctamente.
Se ha cargado el archivo A03235 correctamente.
Se ha cargado el archivo A03236 correctamente.
Se ha cargado el archivo A03237 correctamente.
Se ha cargado el archivo A03238 correctamente.
Se ha cargado el archivo A03239 correctamente.
Se ha cargado el archivo A03240 correctamente.
Se ha cargado el archivo A03241 correctamente.
Se ha cargado el archivo A03242 correctamente.
Se ha cargado el archivo A03243 correctamente.
Se ha cargado el archivo A03244 correctamente.
Se ha cargado el archivo A03245 correctamente.
Se ha cargado el archivo A03246 correctamente.
Se ha cargado el archivo A03247 correctamente.
Se ha cargado el archivo A03248 correctamente.
Se ha cargado el archivo A03249 correctamente.
Se ha cargado el archivo A03250 correctamente.
Se ha cargado el archivo A03251 correctamente.
Se ha cargado el archivo A03252 correctamente.
Se ha cargado el archivo A03253 correctamente.
Se ha cargado el archivo A03254 correctamente.
Se ha cargado el archivo A03255 correctamente.
Se ha cargado el archivo A03256 correctamente.
Se ha cargado el archivo A03257 correctamente.
Se ha cargado el archivo A03258 correctamente.
Se ha cargado el archivo A03259 correctamente.
Se ha cargado el archivo A03260 correctamente.
Se ha cargado el archivo A03261 correctamente.
Se ha cargado el archivo A03262 correctamente.
Se ha cargado el archivo A03263 correctamente.
Se ha cargado el archivo A03264 correctamente.
Se ha cargado el archivo A03265 correctamente.
Se ha cargado el archivo A03266 correctamente.
Se ha cargado el archivo A03267 correctamente.
Se ha cargado el archivo A03268 correctamente.
Se ha cargado el archivo A03269 correctamente.
Se ha cargado el archivo A03270 correctamente.
Se ha cargado el archivo A03271 correctamente.
Se ha cargado el archivo A03272 correctamente.
Se ha cargado el archivo A03273 correctamente.
Se ha cargado el archivo A03274 correctamente.
Se ha cargado el archivo A03275 correctamente.
Se ha cargado el archivo A03276 correctamente.
Se ha cargado el archivo A03277 correctamente.
Se ha cargado el archivo A03278 correctamente.
Se ha cargado el archivo A03279 correctamente.
Se ha cargado el archivo A03280 correctamente.
Se ha cargado el archivo A03281 correctamente.
Se ha cargado el archivo A03282 correctamente.
Se ha cargado el archivo A03283 correctamente.
Se ha cargado el archivo A03284 correctamente.
Se ha cargado el archivo A03285 correctamente.
Se ha cargado el archivo A03286 correctamente.
Se ha cargado el archivo A03287 correctamente.
Se ha cargado el archivo A03288 correctamente.
Se ha cargado el archivo A03289 correctamente.
Se ha cargado el archivo A03290 correctamente.
Se ha cargado el archivo A03291 correctamente.
Se ha cargado el archivo A03292 correctamente.
Se ha cargado el archivo A03293 correctamente.
Se ha cargado el archivo A03294 correctamente.
Se ha cargado el archivo A03295 correctamente.
Se ha cargado el archivo A03296 correctamente.
Se ha cargado el archivo A03297 correctamente.
Se ha cargado el archivo A03298 correctamente.
Se ha cargado el archivo A03299 correctamente.
Se ha cargado el archivo A03300 correctamente.
Se ha cargado el archivo A03301 correctamente.
Se ha cargado el archivo A03302 correctamente.
Se ha cargado el archivo A03303 correctamente.
Se ha cargado el archivo A03304 correctamente.
Se ha cargado el archivo A03305 correctamente.
Se ha cargado el archivo A03306 correctamente.
Se ha cargado el archivo A03307 correctamente.
Se ha cargado el archivo A03308 correctamente.
Se ha cargado el archivo A03309 correctamente.
Se ha cargado el archivo A03310 correctamente.
Se ha cargado el archivo A03311 correctamente.
Se ha cargado el archivo A03312 correctamente.
Se ha cargado el archivo A03313 correctamente.
Se ha cargado el archivo A03314 correctamente.
Se ha cargado el archivo A03315 correctamente.
Se ha cargado el archivo A03316 correctamente.
Se ha cargado el archivo A03317 correctamente.
Se ha cargado el archivo A03318 correctamente.
Se ha cargado el archivo A03319 correctamente.
Se ha cargado el archivo A03320 correctamente.
Se ha cargado el archivo A03321 correctamente.
Se ha cargado el archivo A03322 correctamente.
Se ha cargado el archivo A03323 correctamente.
Se ha cargado el archivo A03324 correctamente.
Se ha cargado el archivo A03325 correctamente.
Se ha cargado el archivo A03326 correctamente.
Se ha cargado el archivo A03327 correctamente.
Se ha cargado el archivo A03328 correctamente.
Se ha cargado el archivo A03329 correctamente.
Se ha cargado el archivo A03330 correctamente.
Se ha cargado el archivo A03331 correctamente.
Se ha cargado el archivo A03332 correctamente.
Se ha cargado el archivo A03333 correctamente.
Se ha cargado el archivo A03334 correctamente.
Se ha cargado el archivo A03335 correctamente.
Se ha cargado el archivo A03336 correctamente.
Se ha cargado el archivo A03337 correctamente.
Se ha cargado el archivo A03338 correctamente.
Se ha cargado el archivo A03339 correctamente.
Se ha cargado el archivo A03340 correctamente.
Se ha cargado el archivo A03341 correctamente.
Se ha cargado el archivo A03342 correctamente.
Se ha cargado el archivo A03343 correctamente.
Se ha cargado el archivo A03344 correctamente.
Se ha cargado el archivo A03345 correctamente.
Se ha cargado el archivo A03346 correctamente.
Se ha cargado el archivo A03347 correctamente.
Se ha cargado el archivo A03348 correctamente.
Se ha cargado el archivo A03349 correctamente.
Se ha cargado el archivo A03350 correctamente.
Se ha cargado el archivo A03351 correctamente.
Se ha cargado el archivo A03352 correctamente.
Se ha cargado el archivo A03353 correctamente.
Se ha cargado el archivo A03354 correctamente.
Se ha cargado el archivo A03355 correctamente.
Se ha cargado el archivo A03356 correctamente.
Se ha cargado el archivo A03357 correctamente.
Se ha cargado el archivo A03358 correctamente.
Se ha cargado el archivo A03359 correctamente.
Se ha cargado el archivo A03360 correctamente.
Se ha cargado el archivo A03361 correctamente.
Se ha cargado el archivo A03362 correctamente.
Se ha cargado el archivo A03363 correctamente.
Se ha cargado el archivo A03364 correctamente.
Se ha cargado el archivo A03365 correctamente.
Se ha cargado el archivo A03366 correctamente.
Se ha cargado el archivo A03367 correctamente.
Se ha cargado el archivo A03368 correctamente.
Se ha cargado el archivo A03369 correctamente.
Se ha cargado el archivo A03370 correctamente.
Se ha cargado el archivo A03371 correctamente.
Se ha cargado el archivo A03372 correctamente.
Se ha cargado el archivo A03373 correctamente.
Se ha cargado el archivo A03374 correctamente.
Se ha cargado el archivo A03375 correctamente.
Se ha cargado el archivo A03376 correctamente.
Se ha cargado el archivo A03377 correctamente.
Se ha cargado el archivo A03378 correctamente.
Se ha cargado el archivo A03379 correctamente.
Se ha cargado el archivo A03380 correctamente.
Se ha cargado el archivo A03381 correctamente.
Se ha cargado el archivo A03382 correctamente.
Se ha cargado el archivo A03383 correctamente.
Se ha cargado el archivo A03384 correctamente.
Se ha cargado el archivo A03385 correctamente.
Se ha cargado el archivo A03386 correctamente.
Se ha cargado el archivo A03387 correctamente.
Se ha cargado el archivo A03388 correctamente.
Se ha cargado el archivo A03389 correctamente.
Se ha cargado el archivo A03390 correctamente.
Se ha cargado el archivo A03391 correctamente.
Se ha cargado el archivo A03392 correctamente.
Se ha cargado el archivo A03393 correctamente.
Se ha cargado el archivo A03394 correctamente.
Se ha cargado el archivo A03395 correctamente.
Se ha cargado el archivo A03396 correctamente.
Se ha cargado el archivo A03397 correctamente.
Se ha cargado el archivo A03398 correctamente.
Se ha cargado el archivo A03399 correctamente.
Se ha cargado el archivo A03400 correctamente.
Se ha cargado el archivo A03401 correctamente.
Se ha cargado el archivo A03402 correctamente.
Se ha cargado el archivo A03403 correctamente.
Se ha cargado el archivo A03404 correctamente.
Se ha cargado el archivo A03405 correctamente.
Se ha cargado el archivo A03406 correctamente.
Se ha cargado el archivo A03407 correctamente.
Se ha cargado el archivo A03408 correctamente.
Se ha cargado el archivo A03409 correctamente.
Se ha cargado el archivo A03410 correctamente.
Se ha cargado el archivo A03411 correctamente.
Se ha cargado el archivo A03412 correctamente.
Se ha cargado el archivo A03413 correctamente.
Se ha cargado el archivo A03414 correctamente.
Se ha cargado el archivo A03415 correctamente.
Se ha cargado el archivo A03416 correctamente.
Se ha cargado el archivo A03417 correctamente.
Se ha cargado el archivo A03418 correctamente.
Se ha cargado el archivo A03419 correctamente.
Se ha cargado el archivo A03420 correctamente.
Se ha cargado el archivo A03421 correctamente.
Se ha cargado el archivo A03422 correctamente.
Se ha cargado el archivo A03423 correctamente.
Se ha cargado el archivo A03424 correctamente.
Se ha cargado el archivo A03425 correctamente.
Se ha cargado el archivo A03426 correctamente.
Se ha cargado el archivo A03427 correctamente.
Se ha cargado el archivo A03428 correctamente.
Se ha cargado el archivo A03429 correctamente.
Se ha cargado el archivo A03430 correctamente.
Se ha cargado el archivo A03431 correctamente.
Se ha cargado el archivo A03432 correctamente.
Se ha cargado el archivo A03433 correctamente.
Se ha cargado el archivo A03434 correctamente.
Se ha cargado el archivo A03435 correctamente.
Se ha cargado el archivo A03436 correctamente.
Se ha cargado el archivo A03437 correctamente.
Se ha cargado el archivo A03438 correctamente.
Se ha cargado el archivo A03439 correctamente.
Se ha cargado el archivo A03440 correctamente.
Se ha cargado el archivo A03441 correctamente.
Se ha cargado el archivo A03442 correctamente.
Se ha cargado el archivo A03443 correctamente.
Se ha cargado el archivo A03444 correctamente.
Se ha cargado el archivo A03445 correctamente.
Se ha cargado el archivo A03446 correctamente.
Se ha cargado el archivo A03447 correctamente.
Se ha cargado el archivo A03448 correctamente.
Se ha cargado el archivo A03449 correctamente.
Se ha cargado el archivo A03450 correctamente.
Se ha cargado el archivo A03451 correctamente.
Se ha cargado el archivo A03452 correctamente.
Se ha cargado el archivo A03453 correctamente.
Se ha cargado el archivo A03454 correctamente.
Se ha cargado el archivo A03455 correctamente.
Se ha cargado el archivo A03456 correctamente.
Se ha cargado el archivo A03457 correctamente.
Se ha cargado el archivo A03458 correctamente.
Se ha cargado el archivo A03459 correctamente.
Se ha cargado el archivo A03460 correctamente.
Se ha cargado el archivo A03461 correctamente.
Se ha cargado el archivo A03462 correctamente.
Se ha cargado el archivo A03463 correctamente.
Se ha cargado el archivo A03464 correctamente.
Se ha cargado el archivo A03465 correctamente.
Se ha cargado el archivo A03466 correctamente.
Se ha cargado el archivo A03467 correctamente.
Se ha cargado el archivo A03468 correctamente.
Se ha cargado el archivo A03469 correctamente.
Se ha cargado el archivo A03470 correctamente.
Se ha cargado el archivo A03471 correctamente.
Se ha cargado el archivo A03472 correctamente.
Se ha cargado el archivo A03473 correctamente.
Se ha cargado el archivo A03474 correctamente.
Se ha cargado el archivo A03475 correctamente.
Se ha cargado el archivo A03476 correctamente.
Se ha cargado el archivo A03477 correctamente.
Se ha cargado el archivo A03478 correctamente.
Se ha cargado el archivo A03479 correctamente.
Se ha cargado el archivo A03480 correctamente.
Se ha cargado el archivo A03481 correctamente.
Se ha cargado el archivo A03482 correctamente.
Se ha cargado el archivo A03483 correctamente.
Se ha cargado el archivo A03484 correctamente.
Se ha cargado el archivo A03485 correctamente.
Se ha cargado el archivo A03486 correctamente.
Se ha cargado el archivo A03487 correctamente.
Se ha cargado el archivo A03488 correctamente.
Se ha cargado el archivo A03489 correctamente.
Se ha cargado el archivo A03490 correctamente.
Se ha cargado el archivo A03491 correctamente.
Se ha cargado el archivo A03492 correctamente.
Se ha cargado el archivo A03493 correctamente.
Se ha cargado el archivo A03494 correctamente.
Se ha cargado el archivo A03495 correctamente.
Se ha cargado el archivo A03496 correctamente.
Se ha cargado el archivo A03497 correctamente.
Se ha cargado el archivo A03498 correctamente.
Se ha cargado el archivo A03499 correctamente.
Se ha cargado el archivo A03500 correctamente.
Se ha cargado el archivo A03501 correctamente.
Se ha cargado el archivo A03502 correctamente.
Se ha cargado el archivo A03503 correctamente.
Se ha cargado el archivo A03504 correctamente.
Se ha cargado el archivo A03505 correctamente.
Se ha cargado el archivo A03506 correctamente.
Se ha cargado el archivo A03507 correctamente.
Se ha cargado el archivo A03508 correctamente.
Se ha cargado el archivo A03509 correctamente.
Se ha cargado el archivo A03510 correctamente.
Se ha cargado el archivo A03511 correctamente.
Se ha cargado el archivo A03512 correctamente.
Se ha cargado el archivo A03513 correctamente.
Se ha cargado el archivo A03514 correctamente.
Se ha cargado el archivo A03515 correctamente.
Se ha cargado el archivo A03516 correctamente.
Se ha cargado el archivo A03517 correctamente.
Se ha cargado el archivo A03518 correctamente.
Se ha cargado el archivo A03519 correctamente.
Se ha cargado el archivo A03520 correctamente.
Se ha cargado el archivo A03521 correctamente.
Se ha cargado el archivo A03522 correctamente.
Se ha cargado el archivo A03523 correctamente.
Se ha cargado el archivo A03524 correctamente.
Se ha cargado el archivo A03525 correctamente.
Se ha cargado el archivo A03526 correctamente.
Se ha cargado el archivo A03527 correctamente.
Se ha cargado el archivo A03528 correctamente.
Se ha cargado el archivo A03529 correctamente.
Se ha cargado el archivo A03530 correctamente.
Se ha cargado el archivo A03531 correctamente.
Se ha cargado el archivo A03532 correctamente.
Se ha cargado el archivo A03533 correctamente.
Se ha cargado el archivo A03534 correctamente.
Se ha cargado el archivo A03535 correctamente.
Se ha cargado el archivo A03536 correctamente.
Se ha cargado el archivo A03537 correctamente.
Se ha cargado el archivo A03538 correctamente.
Se ha cargado el archivo A03539 correctamente.
Se ha cargado el archivo A03540 correctamente.
Se ha cargado el archivo A03541 correctamente.
Se ha cargado el archivo A03542 correctamente.
Se ha cargado el archivo A03543 correctamente.
Se ha cargado el archivo A03544 correctamente.
Se ha cargado el archivo A03545 correctamente.
Se ha cargado el archivo A03546 correctamente.
Se ha cargado el archivo A03547 correctamente.
Se ha cargado el archivo A03548 correctamente.
Se ha cargado el archivo A03549 correctamente.
Se ha cargado el archivo A03550 correctamente.
Se ha cargado el archivo A03551 correctamente.
Se ha cargado el archivo A03552 correctamente.
Se ha cargado el archivo A03553 correctamente.
Se ha cargado el archivo A03554 correctamente.
Se ha cargado el archivo A03555 correctamente.
Se ha cargado el archivo A03556 correctamente.
Se ha cargado el archivo A03557 correctamente.
Se ha cargado el archivo A03558 correctamente.
Se ha cargado el archivo A03559 correctamente.
Se ha cargado el archivo A03560 correctamente.
Se ha cargado el archivo A03561 correctamente.
Se ha cargado el archivo A03562 correctamente.
Se ha cargado el archivo A03563 correctamente.
Se ha cargado el archivo A03564 correctamente.
Se ha cargado el archivo A03565 correctamente.
Se ha cargado el archivo A03566 correctamente.
Se ha cargado el archivo A03567 correctamente.
Se ha cargado el archivo A03568 correctamente.
Se ha cargado el archivo A03569 correctamente.
Se ha cargado el archivo A03570 correctamente.
Se ha cargado el archivo A03571 correctamente.
Se ha cargado el archivo A03572 correctamente.
Se ha cargado el archivo A03573 correctamente.
Se ha cargado el archivo A03574 correctamente.
Se ha cargado el archivo A03575 correctamente.
Se ha cargado el archivo A03576 correctamente.
Se ha cargado el archivo A03577 correctamente.
Se ha cargado el archivo A03578 correctamente.
Se ha cargado el archivo A03579 correctamente.
Se ha cargado el archivo A03580 correctamente.
Se ha cargado el archivo A03581 correctamente.
Se ha cargado el archivo A03582 correctamente.
Se ha cargado el archivo A03583 correctamente.
Se ha cargado el archivo A03584 correctamente.
Se ha cargado el archivo A03585 correctamente.
Se ha cargado el archivo A03586 correctamente.
Se ha cargado el archivo A03587 correctamente.
Se ha cargado el archivo A03588 correctamente.
Se ha cargado el archivo A03589 correctamente.
Se ha cargado el archivo A03590 correctamente.
Se ha cargado el archivo A03591 correctamente.
Se ha cargado el archivo A03592 correctamente.
Se ha cargado el archivo A03593 correctamente.
Se ha cargado el archivo A03594 correctamente.
Se ha cargado el archivo A03595 correctamente.
Se ha cargado el archivo A03596 correctamente.
Se ha cargado el archivo A03597 correctamente.
Se ha cargado el archivo A03598 correctamente.
Se ha cargado el archivo A03599 correctamente.
Se ha cargado el archivo A03600 correctamente.
Se ha cargado el archivo A03601 correctamente.
Se ha cargado el archivo A03602 correctamente.
Se ha cargado el archivo A03603 correctamente.
Se ha cargado el archivo A03604 correctamente.
Se ha cargado el archivo A03605 correctamente.
Se ha cargado el archivo A03606 correctamente.
Se ha cargado el archivo A03607 correctamente.
Se ha cargado el archivo A03608 correctamente.
Se ha cargado el archivo A03609 correctamente.
Se ha cargado el archivo A03610 correctamente.
Se ha cargado el archivo A03611 correctamente.
Se ha cargado el archivo A03612 correctamente.
Se ha cargado el archivo A03613 correctamente.
Se ha cargado el archivo A03614 correctamente.
Se ha cargado el archivo A03615 correctamente.
Se ha cargado el archivo A03616 correctamente.
Se ha cargado el archivo A03617 correctamente.
Se ha cargado el archivo A03618 correctamente.
Se ha cargado el archivo A03619 correctamente.
Se ha cargado el archivo A03620 correctamente.
Se ha cargado el archivo A03621 correctamente.
Se ha cargado el archivo A03622 correctamente.
Se ha cargado el archivo A03623 correctamente.
Se ha cargado el archivo A03624 correctamente.
Se ha cargado el archivo A03625 correctamente.
Se ha cargado el archivo A03626 correctamente.
Se ha cargado el archivo A03627 correctamente.
Se ha cargado el archivo A03628 correctamente.
Se ha cargado el archivo A03629 correctamente.
Se ha cargado el archivo A03630 correctamente.
Se ha cargado el archivo A03631 correctamente.
Se ha cargado el archivo A03632 correctamente.
Se ha cargado el archivo A03633 correctamente.
Se ha cargado el archivo A03634 correctamente.
Se ha cargado el archivo A03635 correctamente.
Se ha cargado el archivo A03636 correctamente.
Se ha cargado el archivo A03637 correctamente.
Se ha cargado el archivo A03638 correctamente.
Se ha cargado el archivo A03639 correctamente.
Se ha cargado el archivo A03640 correctamente.
Se ha cargado el archivo A03641 correctamente.
Se ha cargado el archivo A03642 correctamente.
Se ha cargado el archivo A03643 correctamente.
Se ha cargado el archivo A03644 correctamente.
Se ha cargado el archivo A03645 correctamente.
Se ha cargado el archivo A03646 correctamente.
Se ha cargado el archivo A03647 correctamente.
Se ha cargado el archivo A03648 correctamente.
Se ha cargado el archivo A03649 correctamente.
Se ha cargado el archivo A03650 correctamente.
Se ha cargado el archivo A03651 correctamente.
Se ha cargado el archivo A03652 correctamente.
Se ha cargado el archivo A03653 correctamente.
Se ha cargado el archivo A03654 correctamente.
Se ha cargado el archivo A03655 correctamente.
Se ha cargado el archivo A03656 correctamente.

In [ ]:
dic3 = guardar_señales_valor ("/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento", "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion/df_clasificacion_~.csv", "/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_~")

Se han truncado las últimas 5000 líneas del flujo de salida.
Se ha cargado el archivo A03233 correctamente.
Se ha cargado el archivo A03234 correctamente.
Se ha cargado el archivo A03235 correctamente.
Se ha cargado el archivo A03236 correctamente.
Se ha cargado el archivo A03237 correctamente.
Se ha cargado el archivo A03238 correctamente.
Se ha cargado el archivo A03239 correctamente.
Se ha cargado el archivo A03240 correctamente.
Se ha cargado el archivo A03241 correctamente.
Se ha cargado el archivo A03242 correctamente.
Se ha cargado el archivo A03243 correctamente.
Se ha cargado el archivo A03244 correctamente.
Se ha cargado el archivo A03245 correctamente.
Se ha cargado el archivo A03246 correctamente.
Se ha cargado el archivo A03247 correctamente.
Se ha cargado el archivo A03248 correctamente.
Se ha cargado el archivo A03249 correctamente.
Se ha cargado el archivo A03250 correctamente.
Se ha cargado el archivo A03251 correctamente.
Se ha cargado el archivo A03252 correctamente.
Se ha cargado el archivo A03253 correctamente.
Se ha cargado el archivo A03254 correctamente.
Se ha cargado el archivo A03255 correctamente.
Se ha cargado el archivo A03256 correctamente.
Se ha cargado el archivo A03257 correctamente.
Se ha cargado el archivo A03258 correctamente.
Se ha cargado el archivo A03259 correctamente.
Se ha cargado el archivo A03260 correctamente.
Se ha cargado el archivo A03261 correctamente.
Se ha cargado el archivo A03262 correctamente.
Se ha cargado el archivo A03263 correctamente.
Se ha cargado el archivo A03264 correctamente.
Se ha cargado el archivo A03265 correctamente.
Se ha cargado el archivo A03266 correctamente.
Se ha cargado el archivo A03267 correctamente.
Se ha cargado el archivo A03268 correctamente.
Se ha cargado el archivo A03269 correctamente.
Se ha cargado el archivo A03270 correctamente.
Se ha cargado el archivo A03271 correctamente.
Se ha cargado el archivo A03272 correctamente.
Se ha cargado el archivo A03273 correctamente.
Se ha cargado el archivo A03274 correctamente.
Se ha cargado el archivo A03275 correctamente.
Se ha cargado el archivo A03276 correctamente.
Se ha cargado el archivo A03277 correctamente.
Se ha cargado el archivo A03278 correctamente.
Se ha cargado el archivo A03279 correctamente.
Se ha cargado el archivo A03280 correctamente.
Se ha cargado el archivo A03281 correctamente.
Se ha cargado el archivo A03282 correctamente.
Se ha cargado el archivo A03283 correctamente.
Se ha cargado el archivo A03284 correctamente.
Se ha cargado el archivo A03285 correctamente.
Se ha cargado el archivo A03286 correctamente.
Se ha cargado el archivo A03287 correctamente.
Se ha cargado el archivo A03288 correctamente.
Se ha cargado el archivo A03289 correctamente.
Se ha cargado el archivo A03290 correctamente.
Se ha cargado el archivo A03291 correctamente.
Se ha cargado el archivo A03292 correctamente.
Se ha cargado el archivo A03293 correctamente.
Se ha cargado el archivo A03294 correctamente.
Se ha cargado el archivo A03295 correctamente.
Se ha cargado el archivo A03296 correctamente.
Se ha cargado el archivo A03297 correctamente.
Se ha cargado el archivo A03298 correctamente.
Se ha cargado el archivo A03299 correctamente.
Se ha cargado el archivo A03300 correctamente.
Se ha cargado el archivo A03301 correctamente.
Se ha cargado el archivo A03302 correctamente.
Se ha cargado el archivo A03303 correctamente.
Se ha cargado el archivo A03304 correctamente.
Se ha cargado el archivo A03305 correctamente.
Se ha cargado el archivo A03306 correctamente.
Se ha cargado el archivo A03307 correctamente.
Se ha cargado el archivo A03308 correctamente.
Se ha cargado el archivo A03309 correctamente.
Se ha cargado el archivo A03310 correctamente.
Se ha cargado el archivo A03311 correctamente.
Se ha cargado el archivo A03312 correctamente.
Se ha cargado el archivo A03313 correctamente.
Se ha cargado el archivo A03314 correctamente.
Se ha cargado el archivo A03315 correctamente.
Se ha cargado el archivo A03316 correctamente.
Se ha cargado el archivo A03317 correctamente.
Se ha cargado el archivo A03318 correctamente.
Se ha cargado el archivo A03319 correctamente.
Se ha cargado el archivo A03320 correctamente.
Se ha cargado el archivo A03321 correctamente.
Se ha cargado el archivo A03322 correctamente.
Se ha cargado el archivo A03323 correctamente.
Se ha cargado el archivo A03324 correctamente.
Se ha cargado el archivo A03325 correctamente.
Se ha cargado el archivo A03326 correctamente.
Se ha cargado el archivo A03327 correctamente.
Se ha cargado el archivo A03328 correctamente.
Se ha cargado el archivo A03329 correctamente.
Se ha cargado el archivo A03330 correctamente.
Se ha cargado el archivo A03331 correctamente.
Se ha cargado el archivo A03332 correctamente.
Se ha cargado el archivo A03333 correctamente.
Se ha cargado el archivo A03334 correctamente.
Se ha cargado el archivo A03335 correctamente.
Se ha cargado el archivo A03336 correctamente.
Se ha cargado el archivo A03337 correctamente.
Se ha cargado el archivo A03338 correctamente.
Se ha cargado el archivo A03339 correctamente.
Se ha cargado el archivo A03340 correctamente.
Se ha cargado el archivo A03341 correctamente.
Se ha cargado el archivo A03342 correctamente.
Se ha cargado el archivo A03343 correctamente.
Se ha cargado el archivo A03344 correctamente.
Se ha cargado el archivo A03345 correctamente.
Se ha cargado el archivo A03346 correctamente.
Se ha cargado el archivo A03347 correctamente.
Se ha cargado el archivo A03348 correctamente.
Se ha cargado el archivo A03349 correctamente.
Se ha cargado el archivo A03350 correctamente.
Se ha cargado el archivo A03351 correctamente.
Se ha cargado el archivo A03352 correctamente.
Se ha cargado el archivo A03353 correctamente.
Se ha cargado el archivo A03354 correctamente.
Se ha cargado el archivo A03355 correctamente.
Se ha cargado el archivo A03356 correctamente.
Se ha cargado el archivo A03357 correctamente.
Se ha cargado el archivo A03358 correctamente.
Se ha cargado el archivo A03359 correctamente.
Se ha cargado el archivo A03360 correctamente.
Se ha cargado el archivo A03361 correctamente.
Se ha cargado el archivo A03362 correctamente.
Se ha cargado el archivo A03363 correctamente.
Se ha cargado el archivo A03364 correctamente.
Se ha cargado el archivo A03365 correctamente.
Se ha cargado el archivo A03366 correctamente.
Se ha cargado el archivo A03367 correctamente.
Se ha cargado el archivo A03368 correctamente.
Se ha cargado el archivo A03369 correctamente.
Se ha cargado el archivo A03370 correctamente.
Se ha cargado el archivo A03371 correctamente.
Se ha cargado el archivo A03372 correctamente.
Se ha cargado el archivo A03373 correctamente.
Se ha cargado el archivo A03374 correctamente.
Se ha cargado el archivo A03375 correctamente.
Se ha cargado el archivo A03376 correctamente.
Se ha cargado el archivo A03377 correctamente.
Se ha cargado el archivo A03378 correctamente.
Se ha cargado el archivo A03379 correctamente.
Se ha cargado el archivo A03380 correctamente.
Se ha cargado el archivo A03381 correctamente.
Se ha cargado el archivo A03382 correctamente.
Se ha cargado el archivo A03383 correctamente.
Se ha cargado el archivo A03384 correctamente.
Se ha cargado el archivo A03385 correctamente.
Se ha cargado el archivo A03386 correctamente.
Se ha cargado el archivo A03387 correctamente.
Se ha cargado el archivo A03388 correctamente.
Se ha cargado el archivo A03389 correctamente.
Se ha cargado el archivo A03390 correctamente.
Se ha cargado el archivo A03391 correctamente.
Se ha cargado el archivo A03392 correctamente.
Se ha cargado el archivo A03393 correctamente.
Se ha cargado el archivo A03394 correctamente.
Se ha cargado el archivo A03395 correctamente.
Se ha cargado el archivo A03396 correctamente.
Se ha cargado el archivo A03397 correctamente.
Se ha cargado el archivo A03398 correctamente.
Se ha cargado el archivo A03399 correctamente.
Se ha cargado el archivo A03400 correctamente.
Se ha cargado el archivo A03401 correctamente.
Se ha cargado el archivo A03402 correctamente.
Se ha cargado el archivo A03403 correctamente.
Se ha cargado el archivo A03404 correctamente.
Se ha cargado el archivo A03405 correctamente.
Se ha cargado el archivo A03406 correctamente.
Se ha cargado el archivo A03407 correctamente.
Se ha cargado el archivo A03408 correctamente.
Se ha cargado el archivo A03409 correctamente.
Se ha cargado el archivo A03410 correctamente.
Se ha cargado el archivo A03411 correctamente.
Se ha cargado el archivo A03412 correctamente.
Se ha cargado el archivo A03413 correctamente.
Se ha cargado el archivo A03414 correctamente.
Se ha cargado el archivo A03415 correctamente.
Se ha cargado el archivo A03416 correctamente.
Se ha cargado el archivo A03417 correctamente.
Se ha cargado el archivo A03418 correctamente.
Se ha cargado el archivo A03419 correctamente.
Se ha cargado el archivo A03420 correctamente.
Se ha cargado el archivo A03421 correctamente.
Se ha cargado el archivo A03422 correctamente.
Se ha cargado el archivo A03423 correctamente.
Se ha cargado el archivo A03424 correctamente.
Se ha cargado el archivo A03425 correctamente.
Se ha cargado el archivo A03426 correctamente.
Se ha cargado el archivo A03427 correctamente.
Se ha cargado el archivo A03428 correctamente.
Se ha cargado el archivo A03429 correctamente.
Se ha cargado el archivo A03430 correctamente.
Se ha cargado el archivo A03431 correctamente.
Se ha cargado el archivo A03432 correctamente.
Se ha cargado el archivo A03433 correctamente.
Se ha cargado el archivo A03434 correctamente.
Se ha cargado el archivo A03435 correctamente.
Se ha cargado el archivo A03436 correctamente.
Se ha cargado el archivo A03437 correctamente.
Se ha cargado el archivo A03438 correctamente.
Se ha cargado el archivo A03439 correctamente.
Se ha cargado el archivo A03440 correctamente.
Se ha cargado el archivo A03441 correctamente.
Se ha cargado el archivo A03442 correctamente.
Se ha cargado el archivo A03443 correctamente.
Se ha cargado el archivo A03444 correctamente.
Se ha cargado el archivo A03445 correctamente.
Se ha cargado el archivo A03446 correctamente.
Se ha cargado el archivo A03447 correctamente.
Se ha cargado el archivo A03448 correctamente.
Se ha cargado el archivo A03449 correctamente.
Se ha cargado el archivo A03450 correctamente.
Se ha cargado el archivo A03451 correctamente.
Se ha cargado el archivo A03452 correctamente.
Se ha cargado el archivo A03453 correctamente.
Se ha cargado el archivo A03454 correctamente.
Se ha cargado el archivo A03455 correctamente.
Se ha cargado el archivo A03456 correctamente.
Se ha cargado el archivo A03457 correctamente.
Se ha cargado el archivo A03458 correctamente.
Se ha cargado el archivo A03459 correctamente.
Se ha cargado el archivo A03460 correctamente.
Se ha cargado el archivo A03461 correctamente.
Se ha cargado el archivo A03462 correctamente.
Se ha cargado el archivo A03463 correctamente.
Se ha cargado el archivo A03464 correctamente.
Se ha cargado el archivo A03465 correctamente.
Se ha cargado el archivo A03466 correctamente.
Se ha cargado el archivo A03467 correctamente.
Se ha cargado el archivo A03468 correctamente.
Se ha cargado el archivo A03469 correctamente.
Se ha cargado el archivo A03470 correctamente.
Se ha cargado el archivo A03471 correctamente.
Se ha cargado el archivo A03472 correctamente.
Se ha cargado el archivo A03473 correctamente.
Se ha cargado el archivo A03474 correctamente.
Se ha cargado el archivo A03475 correctamente.
Se ha cargado el archivo A03476 correctamente.
Se ha cargado el archivo A03477 correctamente.
Se ha cargado el archivo A03478 correctamente.
Se ha cargado el archivo A03479 correctamente.
Se ha cargado el archivo A03480 correctamente.
Se ha cargado el archivo A03481 correctamente.
Se ha cargado el archivo A03482 correctamente.
Se ha cargado el archivo A03483 correctamente.
Se ha cargado el archivo A03484 correctamente.
Se ha cargado el archivo A03485 correctamente.
Se ha cargado el archivo A03486 correctamente.
Se ha cargado el archivo A03487 correctamente.
Se ha cargado el archivo A03488 correctamente.
Se ha cargado el archivo A03489 correctamente.
Se ha cargado el archivo A03490 correctamente.
Se ha cargado el archivo A03491 correctamente.
Se ha cargado el archivo A03492 correctamente.
Se ha cargado el archivo A03493 correctamente.
Se ha cargado el archivo A03494 correctamente.
Se ha cargado el archivo A03495 correctamente.
Se ha cargado el archivo A03496 correctamente.
Se ha cargado el archivo A03497 correctamente.
Se ha cargado el archivo A03498 correctamente.
Se ha cargado el archivo A03499 correctamente.
Se ha cargado el archivo A03500 correctamente.
Se ha cargado el archivo A03501 correctamente.
Se ha cargado el archivo A03502 correctamente.
Se ha cargado el archivo A03503 correctamente.
Se ha cargado el archivo A03504 correctamente.
Se ha cargado el archivo A03505 correctamente.
Se ha cargado el archivo A03506 correctamente.
Se ha cargado el archivo A03507 correctamente.
Se ha cargado el archivo A03508 correctamente.
Se ha cargado el archivo A03509 correctamente.
Se ha cargado el archivo A03510 correctamente.
Se ha cargado el archivo A03511 correctamente.
Se ha cargado el archivo A03512 correctamente.
Se ha cargado el archivo A03513 correctamente.
Se ha cargado el archivo A03514 correctamente.
Se ha cargado el archivo A03515 correctamente.
Se ha cargado el archivo A03516 correctamente.
Se ha cargado el archivo A03517 correctamente.
Se ha cargado el archivo A03518 correctamente.
Se ha cargado el archivo A03519 correctamente.
Se ha cargado el archivo A03520 correctamente.
Se ha cargado el archivo A03521 correctamente.
Se ha cargado el archivo A03522 correctamente.
Se ha cargado el archivo A03523 correctamente.
Se ha cargado el archivo A03524 correctamente.
Se ha cargado el archivo A03525 correctamente.
Se ha cargado el archivo A03526 correctamente.
Se ha cargado el archivo A03527 correctamente.
Se ha cargado el archivo A03528 correctamente.
Se ha cargado el archivo A03529 correctamente.
Se ha cargado el archivo A03530 correctamente.
Se ha cargado el archivo A03531 correctamente.
Se ha cargado el archivo A03532 correctamente.
Se ha cargado el archivo A03533 correctamente.
Se ha cargado el archivo A03534 correctamente.
Se ha cargado el archivo A03535 correctamente.
Se ha cargado el archivo A03536 correctamente.
Se ha cargado el archivo A03537 correctamente.
Se ha cargado el archivo A03538 correctamente.
Se ha cargado el archivo A03539 correctamente.
Se ha cargado el archivo A03540 correctamente.
Se ha cargado el archivo A03541 correctamente.
Se ha cargado el archivo A03542 correctamente.
Se ha cargado el archivo A03543 correctamente.
Se ha cargado el archivo A03544 correctamente.
Se ha cargado el archivo A03545 correctamente.
Se ha cargado el archivo A03546 correctamente.
Se ha cargado el archivo A03547 correctamente.
Se ha cargado el archivo A03548 correctamente.
Se ha cargado el archivo A03549 correctamente.
Se ha cargado el archivo A03550 correctamente.
Se ha cargado el archivo A03551 correctamente.
Se ha cargado el archivo A03552 correctamente.
Se ha cargado el archivo A03553 correctamente.
Se ha cargado el archivo A03554 correctamente.
Se ha cargado el archivo A03555 correctamente.
Se ha cargado el archivo A03556 correctamente.
Se ha cargado el archivo A03557 correctamente.
Se ha cargado el archivo A03558 correctamente.
Se ha cargado el archivo A03559 correctamente.
Se ha cargado el archivo A03560 correctamente.
Se ha cargado el archivo A03561 correctamente.
Se ha cargado el archivo A03562 correctamente.
Se ha cargado el archivo A03563 correctamente.
Se ha cargado el archivo A03564 correctamente.
Se ha cargado el archivo A03565 correctamente.
Se ha cargado el archivo A03566 correctamente.
Se ha cargado el archivo A03567 correctamente.
Se ha cargado el archivo A03568 correctamente.
Se ha cargado el archivo A03569 correctamente.
Se ha cargado el archivo A03570 correctamente.
Se ha cargado el archivo A03571 correctamente.
Se ha cargado el archivo A03572 correctamente.
Se ha cargado el archivo A03573 correctamente.
Se ha cargado el archivo A03574 correctamente.
Se ha cargado el archivo A03575 correctamente.
Se ha cargado el archivo A03576 correctamente.
Se ha cargado el archivo A03577 correctamente.
Se ha cargado el archivo A03578 correctamente.
Se ha cargado el archivo A03579 correctamente.
Se ha cargado el archivo A03580 correctamente.
Se ha cargado el archivo A03581 correctamente.
Se ha cargado el archivo A03582 correctamente.
Se ha cargado el archivo A03583 correctamente.
Se ha cargado el archivo A03584 correctamente.
Se ha cargado el archivo A03585 correctamente.
Se ha cargado el archivo A03586 correctamente.
Se ha cargado el archivo A03587 correctamente.
Se ha cargado el archivo A03588 correctamente.
Se ha cargado el archivo A03589 correctamente.
Se ha cargado el archivo A03590 correctamente.
Se ha cargado el archivo A03591 correctamente.
Se ha cargado el archivo A03592 correctamente.
Se ha cargado el archivo A03593 correctamente.
Se ha cargado el archivo A03594 correctamente.
Se ha cargado el archivo A03595 correctamente.
Se ha cargado el archivo A03596 correctamente.
Se ha cargado el archivo A03597 correctamente.
Se ha cargado el archivo A03598 correctamente.
Se ha cargado el archivo A03599 correctamente.
Se ha cargado el archivo A03600 correctamente.
Se ha cargado el archivo A03601 correctamente.
Se ha cargado el archivo A03602 correctamente.
Se ha cargado el archivo A03603 correctamente.
Se ha cargado el archivo A03604 correctamente.
Se ha cargado el archivo A03605 correctamente.
Se ha cargado el archivo A03606 correctamente.
Se ha cargado el archivo A03607 correctamente.
Se ha cargado el archivo A03608 correctamente.
Se ha cargado el archivo A03609 correctamente.
Se ha cargado el archivo A03610 correctamente.
Se ha cargado el archivo A03611 correctamente.
Se ha cargado el archivo A03612 correctamente.
Se ha cargado el archivo A03613 correctamente.
Se ha cargado el archivo A03614 correctamente.
Se ha cargado el archivo A03615 correctamente.
Se ha cargado el archivo A03616 correctamente.
Se ha cargado el archivo A03617 correctamente.
Se ha cargado el archivo A03618 correctamente.
Se ha cargado el archivo A03619 correctamente.
Se ha cargado el archivo A03620 correctamente.
Se ha cargado el archivo A03621 correctamente.
Se ha cargado el archivo A03622 correctamente.
Se ha cargado el archivo A03623 correctamente.
Se ha cargado el archivo A03624 correctamente.
Se ha cargado el archivo A03625 correctamente.
Se ha cargado el archivo A03626 correctamente.
Se ha cargado el archivo A03627 correctamente.
Se ha cargado el archivo A03628 correctamente.
Se ha cargado el archivo A03629 correctamente.
Se ha cargado el archivo A03630 correctamente.
Se ha cargado el archivo A03631 correctamente.
Se ha cargado el archivo A03632 correctamente.
Se ha cargado el archivo A03633 correctamente.
Se ha cargado el archivo A03634 correctamente.
Se ha cargado el archivo A03635 correctamente.
Se ha cargado el archivo A03636 correctamente.
Se ha cargado el archivo A03637 correctamente.
Se ha cargado el archivo A03638 correctamente.
Se ha cargado el archivo A03639 correctamente.
Se ha cargado el archivo A03640 correctamente.
Se ha cargado el archivo A03641 correctamente.
Se ha cargado el archivo A03642 correctamente.
Se ha cargado el archivo A03643 correctamente.
Se ha cargado el archivo A03644 correctamente.
Se ha cargado el archivo A03645 correctamente.
Se ha cargado el archivo A03646 correctamente.
Se ha cargado el archivo A03647 correctamente.
Se ha cargado el archivo A03648 correctamente.
Se ha cargado el archivo A03649 correctamente.
Se ha cargado el archivo A03650 correctamente.
Se ha cargado el archivo A03651 correctamente.
Se ha cargado el archivo A03652 correctamente.
Se ha cargado el archivo A03653 correctamente.
Se ha cargado el archivo A03654 correctamente.
Se ha cargado el archivo A03655 correctamente.
Se ha cargado el archivo A03656 correctamente.

In [16]:
print (len(dic))

2415

In [ ]:
print (len(dic1))

758

In [ ]:
print (len(dic2))

5076

In [ ]:
print (len(dic3))

279

# Función que carga un diccionario en formato pickle

In [17]:
# Hacemos una prueba de que la función es correcta

dic = carga_dic_pickle("/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_A")

Diccionario cargado correctamente desde la ruta: /content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN/señales_A

In [18]:
# Mostramos por pantalla uno de los registros que se ha cargado

senal_A06755 = dic['A06755']

print (senal_A06755)

<wfdb.io.record.Record object at 0x7cfc06761910>